name: Code Quality

on:
  push:

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install Hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc

      - name: Run checks
        run: |
          hatch fmt --check
  type-check:
    name: Type Check
    needs: [format-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install Hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc

      - name: Run type checks
        run: |
          hatch run types:check
  unit-test:
    name: Unit Test
    needs: [format-check, type-check]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc

      - name: Run tests
        if: ${{ matrix.python-version != '3.12' }}
        run: |
          hatch test -i python=${{ matrix.python-version }}

      - name: Run tests with coverage
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          hatch test --cover -i python=${{ matrix.python-version }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}
